#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '- checking your code ...'

npm run check-format ||
(
    echo '❌ Prettier Check Failed.';
    false;
)

npm run check-lint ||
(
    echo '❌ ESLint Check Failed.'
    false; 
)

npm run check-types ||
(
    echo '❌ Failed Type check.'
    false;
)

echo '✅ All Checks Done.'

yarn run lint:style

echo '✅ Stylelint Checks Done.'

yarn lint-staged

echo '✅ Done.'
